baseURL = 'https://jishnuvediyoor.com/'
locale = 'en-us'
title = 'Jishnu Vediyoor'
theme = "PaperMod"
[[menu.main]]
  name = "Collection"
  url = "/collection/"
  weight = 1
[params]
  env = "production"
  description = "Personal website of Jishnu Vediyoor"
  # Custom layouts are designed for a light background only
  defaultTheme = "light"
  disableThemeToggle = true
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/jishnuvediyoor/"

  [[params.socialIcons]]
    name = "instagram"
    url = "https://www.instagram.com/thisconfusedguy/"
